masters/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views 

urlpatterns = [
    path('', include('scrapbook.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scrapbook/urls.py
from django.urls import path
from . import views 
from scrapbook.views import ScrapbookView
from django.contrib.auth import views as auth_views

app_name = 'scrapbook'
urlpatterns = [
    path('', views.index, name='index'),
    path('view/<str:username>/', views.ScrapbookView.as_view(), name='scrapbook_view'),
    path('manage-sharing/<str:username>/', views.manage_sharing, name='manage_sharing'),
    path('manage-sharing/<str:username>/update/', views.delete_collaborator, name='delete_collaborator'),
    path('manage-sharing/<str:username>/add/', views.add_collaborator, name='add_collaborator'),
    path('random-page/<str:username>/', views.random_page, name='random_page'),
    path('create-page/<str:username>', views.PageCreateView.as_view(), name='create_page'),
    path('complete-page/<int:page_pk>', views.complete_page, name='complete_page'),
    path('complete-page/song-search/', views.song_search, name='song_search'),
    path('complete-page/song-save/', views.song_save, name='song_save'),
    path('complete-page/youtube-search/', views.youtube_search, name='youtube_search'),
    path('add-scrapbook/', views.add_scrapbook, name='add_scrapbook'),
    path('add-scrapbook/add-with-code/', views.add_with_code, name='add_with_code'),
    path('update-image/<int:page_pk>/', views.PageImageUpdateView.as_view(), name='image_update'),
    path('update-video/<int:page_pk>/', views.PageVideoUpdateView.as_view(), name='video_update'),
    #path('create-gallery/<int:page_pk>/', views.create_gallery, name='create_gallery'),
    path('view/<int:page_pk>', views.page_view, name='page_view'), 
    path('view/page/add-note/', views.add_note, name='add_note'),
    path('view/page/<int:page_pk>/notes', views.view_notes, name='view_notes'),
    path('activities/', views.activities, name='activities'),
    path('ancestry-search/', views.ancestry, name='ancestry'),
    path('help/', views.help_page, name='help'),
    path('login', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register', views.register, name='register'),
    path('account-help', views.account_recovery, name='account_recovery'),
    path('access-denied', views.no_access, name='no_access'),
    path('password_reset', views.password_reset_request, name='password_reset'),
    path('check-username/', views.check_username, name='check_username'),
]

scrapbook/forms.py
from django.contrib.auth.models import User
from django.forms import ClearableFileInput, FileField, ImageField, ModelForm, TextInput, URLInput
from django import forms
from django.contrib.auth.forms import UserCreationForm
from pyparsing import Char


from scrapbook.models import Page

ROLES =[('owner', 'I want to make a scrapbook'),
        ( 'contributor', 'I want to help someone with their scrapbook'), 
        ('own/contrib', 'I want to do both'),]

RELATIONSHIPS =[ ('own', 'Me'),
                ('partner/spouse', 'Partner/Spouse'), 
                ('child', 'Child'), 
                ('friend', 'Friend'), 
                ('carer', 'Carer/Assistant')]

class RegForm(UserCreationForm):

        recovery_email = forms.EmailField(label='If you need to reset your password, what email should we send the reset link to?')
        recovery_relationship = forms.CharField(label='Who does this email belong to?', widget=forms.Select(choices=RELATIONSHIPS))
        role = forms.CharField(label='What would you like to use Scrapbook for?', widget=forms.Select(choices=ROLES))
        
        class Meta:
                model = User
                fields = ['username', 'password1', 'password2', 'first_name', 'recovery_email', 'recovery_relationship', 'role',]
        
        def save(self, commit=False):
                user = super(RegForm, self).save(commit=False)
                if commit:
                        user.set_password(user.password)
                        user.save() 
                return user

class PageForm(forms.ModelForm):
        class Meta:
                model = Page 
                fields = ('title', 'video_file', 'image_file')
                widgets = {
                        'title': forms.TextInput(attrs={'class': 'form-group', 'label':'Give your page a title'}),
                        'video_file': forms.FileInput(attrs={'class': 'form-group', 'label':'Upload a video here or use YouTube in a later step'}), 
                        'image_file': forms.FileInput(attrs={'class': 'form-group', 'label':'Upload a picture'}),
                }
                labels = {
                        'title': 'Give Your Page a Title',
                        'video_file': 'Upload a Video Here or Use YouTube in a Later Step',
                        'image_file': 'Upload a Picture'
                }

        
# class UserForm(ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput())
    
    
#     class Meta:
#         model = User
#         fields = ('username', 'email', 'password', 'first_name')
        









# class PageForm(ModelForm):
#     class Meta:
#         model = Page
#         fields = ['title', 'video_url', 'video_file', 'song_id']
        
#         widgets = {
#             'title': TextInput(attrs={
#                 'class' : 'form-control', 
#                 'style': 'max-width: 300px;', 
#                 'placeholder': 'Enter a title...'
#                 }),
#             'video_url': URLInput(attrs={
#                 'class': "form-control",
#                 'style': 'max-width: 300px;', 
#                 'placeholder': 'Copy a YouTube link here...' 
#             }),
#             'video_file': ClearableFileInput(attrs={
#                 'class' : 'form-control'
                
#             }), 
#             'song_id': TextInput(attrs={
#                 'class' : 'form-control',
                
#             })
#         }

scrapbook/views.py
#from typing_extensions import Required
from asyncio import subprocess
from cgitb import reset
import os
from django.contrib.auth.decorators import login_required 
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect

from masters.settings import SESSION_EXPIRE_AT_BROWSER_CLOSE 
from .models import Image, Page, Scrapbook, User, TextNote, Account
from scrapbook.forms import PageForm, RegForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect 
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, View
from django.views.generic.edit import CreateView, UpdateView
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from django.http import JsonResponse
import json 
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import date
import random
from pathlib import Path
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q 
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib.auth import authenticate
from django.conf import settings

# Create your views here.
def index(request): 
    context = {}

    
    if request.user.is_authenticated:
        user = request.user
        account = Account.objects.get(user=user)
        context['account'] = account
        
        context['books'] = []
        scrapbooks = Scrapbook.objects.filter(collaborators__id=user.id)
        if account.shares_scrapbook:
            for book in scrapbooks: 
                print(book)
                context['books'].append(book)
        
    return render(request, 'scrapbook/index.html', context)

# class based view for listing all pages in the given scrapbook
class ScrapbookView(LoginRequiredMixin, ListView):
    model = Page 
    
    template_name = 'scrapbook/scrapbook_view.html'
    
    def get_queryset(self):
        self.user = get_object_or_404(User, username=self.kwargs['username'])
        self.scrapbook = get_object_or_404(Scrapbook, owner=self.user)
        
        self.viewable = False
        self.is_owner = False 
        
        if self.user == self.request.user:
            self.viewable = True 
            self.is_owner = True
        else:
            self.current_collaborator = self.scrapbook.collaborators.filter(username=self.request.user.username)
            if self.current_collaborator:
                self.viewable = True
                self.is_owner = False
            else:
                self.viewable = False
                return reverse_lazy('scrapbook:index')
        
        if not self.viewable:
            return reverse_lazy('scrapbook:no_access')
        return Page.objects.filter(scrapbook=self.scrapbook)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.user.username 
        context['scrapbook'] = self.scrapbook
        context['viewable'] = self.viewable 
        context['is_owner'] = self.is_owner
            
        return context

@login_required
def manage_sharing(request, username):
    owner = get_object_or_404(User, username=username)
    scrapbook = get_object_or_404(Scrapbook, owner=owner)
    if request.user != scrapbook.owner: 
        return redirect(reverse('scrapbook:index'))
    
    collaborators = []
    for c in scrapbook.collaborators.all():
        collaborators.append(c)
            
    context = {}
    context['collaborators'] = collaborators
    context['scrapbook'] = scrapbook
    
    
    return render(request,'scrapbook/manage_sharing.html', context)

@login_required
def delete_collaborator(request, username):
    owner = get_object_or_404(User, username=username)
    scrapbook = get_object_or_404(Scrapbook, owner=owner)
    if request.user != scrapbook.owner: 
        return redirect(reverse('scrapbook:index'))
    
    if is_ajax(request):
        data = json.load(request)
        user = User.objects.get(username=data['removed_collab'])
        print(user)
        print(scrapbook)
        scrapbook.collaborators.remove(user)
        scrapbook.save()
        return JsonResponse(data)
    return

@login_required
def add_collaborator(request, username):
    owner = get_object_or_404(User, username=username)
    scrapbook = get_object_or_404(Scrapbook, owner=owner)
    if request.user != scrapbook.owner: 
        return redirect(reverse('scrapbook:index'))
    
    if is_ajax(request):
        data = json.load(request)
        user = User.objects.get(username=data['add_collab'])
        if not user:
            error = {'message': "no user"}
            return JsonResponse(error)
        scrapbook.collaborators.add(user)
        scrapbook.save()
        return JsonResponse(data)
    
    
def add_scrapbook(request):
    context = {}
    context['user'] = request.user 
    context['account'] = Account.objects.get(user=context['user'])
    return render(request,'scrapbook/add_scrapbook.html', context)
    
    
def add_with_code(request):
    if is_ajax(request):
        response = {}
        data = json.load(request)
        code = data['code']
        
        try:
            scrapbook = Scrapbook.objects.get(share_code=code)
            response['user'] = scrapbook.owner.username
            scrapbook.collaborators.add(request.user)
            
        except Scrapbook.DoesNotExist:
            response['user'] = 'none'
            
        print(response['user'])
        return JsonResponse(response)

            

@login_required
def random_page(request, username):
    owner = User.objects.get(username=username)
    scrapbook = Scrapbook.objects.get(owner=owner)
    pages = Page.objects.filter(scrapbook=scrapbook)
    rand_page = random.choice(pages) 
    return redirect('scrapbook:page_view', page_pk=rand_page.id)



#                   PAGE CREATION 
##############################################################

class PageCreateView(LoginRequiredMixin, CreateView):
    model = Page
    form_class = PageForm
    template_name = 'scrapbook/create_page.html'
    
    def get_success_url(self) -> str:
        return reverse_lazy('scrapbook:complete_page', kwargs={'page_pk': self.object.pk})
    
    def get_context_data(self, **kwargs):
        context = super(PageCreateView, self).get_context_data(**kwargs)
        context['username'] = self.request.user.username
        return context
    
    def form_valid(self, form): 
        form.instance.creator = self.request.user 
        form.instance.scrapbook = get_object_or_404(Scrapbook, owner=get_object_or_404(User, username=self.kwargs['username']))
        
        return super().form_valid(form)

        
@login_required
def complete_page(request, page_pk):
    page = get_object_or_404(Page, id=page_pk)
    context = {}
    
    current_user = request.user 
    
    if current_user != page.creator:
        return redirect(reverse('scrapbook:index'))

    context['user'] = current_user
    context['page'] = page
    context['yt_key'] = settings.YT_API_KEY
    context['yt_client_id'] = settings.YT_CLIENT_ID
    return render(request,'scrapbook/complete_page.html', context)



@login_required
def song_search(request):
    if is_ajax(request):
        spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials(client_id=settings.SPOTIPY_CLIENT_ID, client_secret=settings.SPOTIPY_CLIENT_SECRET))
        data = json.load(request)
        artist = data['artist']
        title = data['song_title']
        
        q = " track:" + title 
        print(q)
        if artist: 
            q = q + " artist:" + artist
            
        q.replace(" ", "%20")
        print(q)
        result = spotify.search(q, 5, 0, "track")
        response = {}
        no_of_results = len(result['tracks']['items'])
        print(no_of_results)
        
        
        embedPre = "https://open.spotify.com/embed/track/"
        embedPost = "?utm_source=generator"
        
        response['resultsNum'] = no_of_results
        
        if no_of_results >= 1:
            embed1 = embedPre + result['tracks']['items'][0]['id'] + embedPost
            response['result 1'] = embed1
        if no_of_results >= 2:
            embed2 = embedPre + result['tracks']['items'][1]['id'] + embedPost
            response['result 2'] = embed2
        if no_of_results >= 3:
            embed3 = embedPre + result['tracks']['items'][2]['id'] + embedPost
            response['result 3'] = embed3
        if no_of_results >= 4:
            embed4 = embedPre + result['tracks']['items'][3]['id'] + embedPost
            response['result 4'] = embed4
            
      
            
        return JsonResponse(response)
    
@login_required
def song_save(request):
    if is_ajax(request):
        data = json.load(request)
        print(data['embed'])
        print(data['page_id'])
        page = get_object_or_404(Page, id=data['page_id'])
        page.song_embed = data['embed']
        page.save()
        vid_required = False
        if bool(page.video_file) == False:
            vid_required = True
        response = {}
        response['vid_required'] =  vid_required
        print(response['vid_required'])
     
        return JsonResponse(response)
    
    return 

@login_required
def youtube_search(request):
    if is_ajax(request):
        data = json.load(request)
        page = get_object_or_404(Page, id=data['page_id'])
        page.vid_src = data['src']
        print('got to views ajax ')
        page.save()
        context = {}
        context['page'] = page
        context['user'] = request.user
        return JsonResponse(data)
    

scrapbook/templates/scrapbook/login.html
{% extends 'scrapbook/base.html' %} 
{% load static %}

{% block page_title %} 
    <h1 class="fancy">Log In</h1>
{% endblock %}
{% block body_block %}
<link href="{% static 'scrapbook/css/login.css' %}" rel="stylesheet">

<div class="container">
    <div id="login" class="row justify-content-center">
        <div class="card" id="login">
            <div class="card-body">
                <h3 class="card-title">Log In</h3>
                <form id="login_form" method="post" action="{% url 'scrapbook:login' %}">
                    {% csrf_token %} 
                    <div class="form-group-sm">
                        <label>Username:</label>
                        {{ form.username }}
                        <input class="col-xs-12" type="text" name="username" value="" size="40%"/>
                    </div>
                    
                    <div class="form-group-sm">
                        <label>Password: </label>
                        {{ form.password }}
                        <input class="col-xs-12" type="password" name="password" value="" size="40%"/>
                    </div>
                    <h5 class="text-danger">{{ errors }}</h5>
                    <div class="form-group-sm">
                        <label>Keep Me Logged In <br>Not recommended for public or shared devices</label>
                        <input name="remember_me" value="remember_me" type="checkbox">
                    </div>
                    <button id="login_button" class="button btn btn-md btn-success mb-2" type="submit" value="submit">Log In</button>
                </form>
                <a href="{% url 'scrapbook:password_reset' %}"><button class="btn btn-md btn-danger">I'm not sure of my password</button></a>
            </div>
        </div> 
    </div>
   
{% endblock %}

scrapbook/templates/scrapbook/no_access.html
You do not have access to this page. 

scrapbook/templates/scrapbook/page_form.html
{% extends 'scrapbook/base.html' %} 

{% block body_block %} 
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="DONE">
</form>
{% endblock %}

scrapbook/templates/scrapbook/page_view.html
{% extends 'scrapbook/base.html' %}
{% load static %}

    {% block page_title %} 
        <h2 class="fancy">{{ page.title }} <br>({{ scrapbook.owner.first_name }}'s Scrapbook)</h2>
    {% endblock %}

    {% block extra_button %} 
        <a href="{% url 'scrapbook:scrapbook_view' username=page.scrapbook.owner.username %}"><button id="back" class="btn btn-primary"><strong>BACK</strong></button></a> 
    {% endblock %}
{% block body_block %} 

<link href="{% static 'scrapbook/css/page_view.css' %}" rel="stylesheet">


<!-- PAGE -->

<div class="container-fluid">
    <div class="row justify-content-center">
        <h4 class="fancy">Page Created By: {{page.creator.first_name}}</h4>
    </div>
    <!-- row for video, notes and image-->
    <div class="row px-4">
        <div class="col-sm-4 ">
            {% if page.video_file %}
            <video class="embed-responsive-4by3" id="uploaded_vid" source src="{{ MEDIA_URL }}{{page.video_file}}" type="video/mp4"controls width="100%" height="90%">
                <source src="{{ MEDIA_URL }}{{page.video_file}}" type="video/mp4">
                <source src="{{ MEDIA_URL }}{{page.video_file}}" type="video/webm">
                <source src="{{ MEDIA_URL }}{{page.video_file}}" type="video/ogv">
                <p>Sorry, your internet browser is having trouble with playing videos on the page.</p> 
            </video>
            {% elif page.vid_src %}
                <iframe id="youtube" width="100%" height="100%" src="" 
                frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
            {% else %} 
                <a href="{% url 'scrapbook:video_update' page_pk=page.id %}"><button class="btn btn-success">No video yet. Add now.</button></a>
            {% endif %}
        </div>
        <div class="col-sm-4 justify-content-center">
            <div class="container">
                <div id="note_card" class="card">
                    <div  class="card-body">
                        <div class="card-title">
                            <h6 class="text-center fancy">ADD A NOTE</h6>
                        </div>
                        <h6 class="card-subtitle">Title</h6>
                        <div class="form-group">
                            <input id="title_input" class="form-control txtarea"></input>
                        </div>
                        <h6 class="card-subtitle">Note</h6>
                        <div class="form-group">
                            {% csrf_token %}
                            <textarea class="form-control txtarea" id="add_note" rows="3"></textarea>
                        </div>
                        
                        <button class="btn btn-sm btn-success" id="add">
                        <h5><strong>ADD</strong></h5></button>
                        <button id="modal_button" type="button" class="btn btn-sm btn-success border border-dark" data-toggle="modal" data-target="#myModal">
                            <h6><strong>Open Notes</strong></h6>
                        </button>
                    </div>
                </div>
                <hr>
                
            </div>
        </div>
        <div class="col-sm-4 px-0">
            {% if page.image_file %}
                <img class="img-fluid" id="picture" src="{{ MEDIA_URL }}{{page.image_file}}" alt="Your chosen image for {{page.title}}" />
            {% else %} 
                <a href="{% url 'scrapbook:image_update' page_pk=page.id %}"><button class="btn btn-success justify-content-center">No image yet<br> Add now</button></a>
            {% endif %}
            </div>
            
    </div>


    <!-- row for song-->
    <div id="spotify_row" class="row">
        <div class="col-sm-2 ">
            {% if owner  %}
            <a href="{% url 'scrapbook:manage_sharing' username=scrapbook.owner.username %}">
            <button id="sharing" class="btn">SHARING SETTINGS</button></a>
            {% endif %}
        </div>
        <div class="col-sm-8 ">
        <iframe id="spotify" src="" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
        </div>
        <div class="col-sm-2">
            <a href="{% url 'scrapbook:activities' %}">
            <button id="activities" class="btn btn-success">ACTIVITY<br>IDEAS</button>
            </a>
        </div>
    </div>

</div>


<div id="player"></div> 


<!-- NOTES MODAL -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
  
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Notes About {{page.title}}</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
  
        <!-- Modal body -->
        <div class="modal-body">
          <div class="container">
            {% if notes %} 
                {% for note in notes %} 
                <div class="row">
                    <div class="col-sm-12 card mb-3 note">
                        <div class="card-body">
                            <h5 class="card-title fancy">{{note.title}}</h5>
                            <p>{{ note.text }}</p>
                            <br>
                            <p><strong>By: {{note.creator}}</strong></p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %} 
                <h1>No notes yet.</h1>
            {% endif %}
          </div>
        </div>
  
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
  
      </div>
    </div>
  </div>






<script type="text/javascript">

    var page_pk = "{{page.id}}";
    window.onload = function()
    {
        var url = "{{ page.song_embed }}"
    
        // Set an ID for the iframe. Let us give that an id of myframe
        document.getElementById("spotify").setAttribute("src", url);
      
        var vidSrc = "{{ page.vid_src }}"
        document.getElementById("youtube").setAttribute("src", vidSrc);

    }

</script>


<script type="text/javascript" src="{% static 'scrapbook/js/page_view.js' %}"> </script>
{% endblock %}

scrapbook/templates/scrapbook/register.html
{% extends 'scrapbook/base.html' %}
{% load static %} 

{% block page_title %} 
<h1 class="fancy">Registration</h1>
{% endblock %}

{% block body_block %}
{% if registered %} 
    registered
{% else %} 

<link href="{% static 'scrapbook/css/register.css' %}" rel="stylesheet">
<div id="box" class="container-fluid justify-content-center border border-dark">
    <div class="row">
        <div class="col text-center mt-5">
                <h2>Register For Scrapbook</h2>
                <hr>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
            <form id="user_form" method="post" action="{% url 'scrapbook:register' %}" enctype="multipart/form-data">
                {% csrf_token %} 
                <div class="container-fluid">
                    {% for field in form %} 
                    
                        <div class="row form-group">
                            {{ field.errors}}
                            <div class="col-form-label-md">
                            {{ field.label_tag}}  {{field}}
                            </div>
                        </div>
                    {% endfor %}
                        <div class="row">
                            <h5 class="text-danger mt-0">Put your own email if possible. If you need to put another <strong>make sure you trust them with the contents of your scrapbook</strong></h5>
                        </div>
                        <div class="row">
                            <input class="btn" id="register" type="submit" name="submit" value="Register"/>
                        </div>
                </div>
            </form>

    </div>
</div>
{% endif %} 
{% endblock %}

scrapbook/templates/scrapbook/scrapbook_view.html
{% extends 'scrapbook/base.html' %} 
{% load static %} 


{% block body_block %}

<link href="{% static 'scrapbook/css/scrapbook_view.css' %}" rel="stylesheet">

<div class="container-fluid px-0 mx-0">
    <div class="row mx-5 mb-4">
        <div class="col-sm-4 mt-3">
            <div id="create-card" class="card big_card" >
                <a href="{% url 'scrapbook:create_page' username=username %}">
                    <img id="add-icon"  class="card-img-top" src="{% static 'scrapbook/images/add.png' %}" alt="add button">
                        <div class="card-body card-block">
                            <h4 id="new_page" class="card-title">Create New Page</h4>
                        </div>
                </a>
            </div> 
        </div>
        {% if page_list %} 
        <div class="col-sm-4 mt-3 ">
            <div id="random-card" class="card big_card" >
                
                <a href="{% url 'scrapbook:random_page' username=username %}">
                    <img id="shuffle-icon" class="card-img-top" src="{% static 'scrapbook/images/shuffle.png' %}" alt="a shuffle button">
                        <div id="random_text" class="card-body card-block text-center">
                            <h4 class="card-title">Go Down Memory Lane<br></h4><h6 class="text-center">(random page)</h6>
                        </div>
                </a>
            </div>    
        </div>
        {% else %} 
        <div class="col-sm-4 mt-3 ">
            <div id="random-card" class="card" >
                <a href="">
                    <img id="shuffle-icon" class="card-img-top" src="{% static 'scrapbook/images/shuffle.png' %}" alt="a shuffle button">
                        <div id="random_text" class="card-body card-block text-center">
                            <h4 class="card-title">Go Down Memory Lane<br></h4><h6 class="text-center">(Add Pages First)</h6>
                        </div>
                </a>
            </div>    
        </div>
        {% endif %}
            
        <div class="col-sm-4 mt-3">
            <div id="activity_card" class="card big_card" >
                <a href="{% url 'scrapbook:activities' %}">
                    <img id="paint_icon" class="card-img-top" src="{% static 'scrapbook/images/paintbrush.png' %}" alt="a paintbrush">
                        <div id="activity_text" class="card-body card-block text-center">
                            <h4 class="card-title">Go To Activities</h4>
                        </div>
                    </a>
                </div>
            </a>    
        </div>
    </div>
    <div class="row mb-2 justify-content-center">
            {% if is_owner %}
            <div class="col-sm-12" id="sharing" >
                <a href="{% url 'scrapbook:manage_sharing' username=scrapbook.owner.username %}" class="text-center">
                <div id="settings" class="btn btn-success card"><button id="code_button" class="btn btn-md btn-warning"><h5><strong>{{scrapbook.share_code}}</h5></button><h5>View Sharing Settings</h5></div></a>
            </div>  
            {% endif %}    
        </div>         
    </div>
        <div  id="content" class="row mt-3">
            <h1 class="fancy title mx-auto text-center mb-4">Contents</h1>
        </div>
        <div class="row">
        {% if page_list %} 
            <div class="container-fluid">
            <div class="row">
            {% for page in page_list %} 
            <div id="pages_col" class="col-sm-3">
                <a href="{{ page.get_absolute_url }}">
                <div class="card" style="width: 14rem;" data-aos="zoom-in">
                    <img style="height: 10rem;" class="card-img-top" src="{{ MEDIA_URL }}{{page.image_file}}" alt="{{page.title}} image">

                    <div id="title" class="card-body card-block">
                        <h3 id="card-link" class="card-title fancy py-auto">{{page.title}}</h3>
                    </div>
                </div>
                </a>   
            </div>
            {% endfor %}
        {% else %} 
        <div class="container-fluid justify-content-center">
            <div class="row text-center">
                <div class="col-sm-12">
                    <h3 class="text-center">No pages yet. Click 'Create New Page' to get started. </h3> 
                </div>
                
            </div>
        </div>
        {% endif %}
        </div>
        </div>
    

</div>
<script type="text/javascript" src="{% static 'scrapbook/js/scrapbook_view.js' %}"> </script>
{% endblock %}